 DROP TABLE STUDENTS CASCADE CONSTRAINT;
 DROP TABLE BOOKS CASCADE CONSTRAINT;
 DROP TABLE BORROW CASCADE CONSTRAINT;
 DROP TABLE RESERVE CASCADE CONSTRAINT;
 DROP TRIGGER BORROW_AMO;
 DROP TRIGGER increase_book_amount;